### ISSUE TITLE
Finetuning Caffe Models in DIGITS

### ISSUE THREAD

**Issue by RadicoLabs** [NVIDIA/DIGITS#360]
How does one import a googleNet model for training? I noticed the post at [#49](https://github.com/NVIDIA/DIGITS/issues/49#issuecomment-99533854) and [here](http://caffe.berkeleyvision.org/gathered/examples/finetune_flickr_style.html) and tried to follow along, but i keep getting errors!

I downloaded the Googlenet model from the model zoo, then after adjusting job settings, choosing data set, etc i copied the googlenet train_val.prototxt to the custom Network textarea, and then type the direct filepath (i.e. /home/dev/Caffe/model/bvlc_googlenet.caffemodel) into the Pretrained model field and hit create

However, for some reason DIGITS keeps crashing and dumping this error:

    Traceback (most recent call last):
      File "/home/dev/DIGITS/digits/scheduler.py", line 454, in run_task
        task.run(resources)
      File "/home/dev/DIGITS/digits/task.py", line 179, in run
        self.before_run()
      File "/home/dev/DIGITS/digits/model/tasks/caffe_train.py", line 104, in before_run
        self.save_files_classification()
      File "/home/dev/DIGITS/digits/model/tasks/caffe_train.py", line 190, in save_files_classification
        assert not train_data_layer.data_param.HasField('source'), "don't set the data_param.source"
     AssertionError: don't set the data_param.source

Any idea what the go is?

**Comment by lukeyeager** [comment]
In your `.prototxt` file, you'll see something like this:
```
layer {
  name: "data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  data_param {
    source: "/raid/jobs/dev/20150717-143415-5194/train_db"
    batch_size: 24
    backend: LMDB
  }
}
```
Comment out the `data_param.source` and `data_param.backend` lines.
```
  data_param {
#    source: "/raid/jobs/dev/20150717-143415-5194/train_db"
    batch_size: 24
#    backend: LMDB
  }
```

**Comment by RadicoLabs** [comment]
Next error: 

    ERROR: Check failed: mean_values_.size() == 1 || mean_values_.size() == datum_channels Specify either 1 mean_value or as many as channels: 3
    Top shape: 15 480 14 14 (1411200)
    Top shape: 15 480 14 14 (1411200)
    Top shape: 15 480 14 14 (1411200)
    Creating layer inception_4a/1x1
    Creating Layer inception_4a/1x1
    inception_4a/1x1 <- pool3/3x3_s2_pool3/3x3_s2_0_split_0
    inception_4a/1x1 -> inception_4a/1x1
    Setting up inception_4a/1x1
    Top shape: 15 192 14 14 (564480)
    Creating layer inception_4a/relu_1x1
    Creating Layer inception_4a/relu_1x1
    inception_4a/relu_1x1 <- inception_4a/1x1
    inception_4a/relu_1x1 -> inception_4a/1x1 (in-place)
    Setting up inception_4a/relu_1x1
    Top shape: 15 192 14 14 (564480)
    Creating layer inception_4a/3x3_reduce
    Creating Layer inception_4a/3x3_reduce
    inception_4a/3x3_reduce <- pool3/3x3_s2_pool3/3x3_s2_0_split_1
    inception_4a/3x3_reduce -> inception_4a/3x3_reduce
    Setting up inception_4a/3x3_reduce

**Comment by lukeyeager** [comment]
Can you paste the contents of your Data layers? Are you really trying to pass 2 mean values?

**Comment by RadicoLabs** [comment]
I just copied the Train_val.prototxt unmodified... Im entirely new to finetuning models in DIGITS and the process is pretty well undocumented so i've probably made a stupid mistake somewhere - I've attached my deploy, train_val, and solver files for you to look at!

**Comment by lukeyeager** [comment]
I updated your post to include only the data layers.

Your data layer looks right. I bet what's happening is that DIGITS is adding 3 more "mean_value" values to each data layer, for a total of 6 mean values. Can you confirm that's what's happening by looking at the `train_val.prototxt` that DIGITS generates on the next page?

Try either (1) removing those `mean_value: 123` lines or (2) asking DIGITS not to subtract the mean file (under "Data Transformations").

**Comment by RadicoLabs** [comment]
Can confirm that DIGITS is appending an additional 3 mean vals:
```
  transform_param {
    mirror: false
    crop_size: 224
    mean_value: 104.0
    mean_value: 117.0
    mean_value: 123.0
    mean_value: 94.9827728271
    mean_value: 105.82069397
    mean_value: 124.092437744
  }
```


Is this a bug? And if i ask DIGITS to not subtract the mean files, will this affect training or the overall accuracy of our model?

**Comment by lukeyeager** [comment]
> Is this a bug?

Yes, this is a bug. I'll file it separately.

> And if i ask DIGITS to not subtract the mean files, will this affect training or the overall accuracy of our model?

Probably. You should fix this with either (1) or (2) above, but not with both.

**Comment by RadicoLabs** [comment]
Which would you recommend? And lastly, Is there a way to private message on Git? Would like to talk to you if you have the chance!

**Comment by lukeyeager** [comment]
> Which would you recommend?

I'd suggest letting DIGITS set the mean value of your new training images, as that will hopefully be a more significant mean value to use during inference than the original mean (from ImageNet, probably) would be.

> Is there a way to private message on Git? Would like to talk to you if you have the chance!

There's not. I'll reach out to you on your hotmail account.

**Comment by RadicoLabs** [comment]
Saving the day again! @lukeyeager is my hero

**Comment by RadicoLabs** [comment]
So turns out that the 365 fix doesnt fix everything 

still getting error: ERROR: Check failed: ShapeEquals(proto) shape mismatch (reshape not set)

**Comment by lukeyeager** [comment]
As a follow-up to this, the [unhelpful] error message "shape mismatch" is often caused by forgetting to rename a layer in your network when you're fine-tuning. Any layer which has a different size in the new network (i.e. the last fully-connected layer for a different # of classes) needs a new name - like `ip2-retrain` instead of `ip2`, for example.
